session_name: Phala dev env
windows:
  - window_name: dev env
    layout: tiled
    panes:
      - shell_command:
          - ./component-starter.sh node
      - shell_command:
          - ./component-starter.sh pruntime
      - shell_command:
          - ./component-starter.sh pherry
